# Generated by Django 3.2.5 on 2023-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Softdesk', '0002_auto_20230826_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assigned_to_user_id',
            new_name='assigned_to',
        ),
    ]
